// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6R5U3CdhbE3GL5rOnsSntWocZN8RcXAg',
    appId: '1:415493360344:android:1dd32998f76b7f2adbe5ad',
    messagingSenderId: '415493360344',
    projectId: 'flutter-start-dc9a1',
    storageBucket: 'flutter-start-dc9a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmq21yVfasGf_bVYEzELWDbT8a39eGsU',
    appId: '1:415493360344:ios:7c4728affee184e7dbe5ad',
    messagingSenderId: '415493360344',
    projectId: 'flutter-start-dc9a1',
    storageBucket: 'flutter-start-dc9a1.appspot.com',
    iosBundleId: 'io.skolsic.fluttList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwmq21yVfasGf_bVYEzELWDbT8a39eGsU',
    appId: '1:415493360344:ios:7c4728affee184e7dbe5ad',
    messagingSenderId: '415493360344',
    projectId: 'flutter-start-dc9a1',
    storageBucket: 'flutter-start-dc9a1.appspot.com',
    iosBundleId: 'io.skolsic.fluttList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh2gfAvYb6dEzvlP9chcsfmACCdHcupz8',
    appId: '1:415493360344:web:dcce38374634efa3dbe5ad',
    messagingSenderId: '415493360344',
    projectId: 'flutter-start-dc9a1',
    authDomain: 'flutter-start-dc9a1.firebaseapp.com',
    storageBucket: 'flutter-start-dc9a1.appspot.com',
    measurementId: 'G-ZSL6GQFLZM',
  );
}
